### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by Ravencentric** [dhrinkino/PlexRichPresence#1]
Tried both portable and installation but the GUI never showed up, a broken icon did show up in tray and web browser opened for sign-in but it crashes soon after.

**Comment by dhrinkino** [comment]
Try download source code, open it with Visual Studio, and try describe what kind of error you will receive. During first run, application is waiting for authorization with plex account

**Comment by dhrinkino** [comment]
Just now i tried released version, after authorization with plex, application will stay minimalized but you can show it from taskbar

**Comment by Ravencentric** [comment]
> Try download source code, open it with Visual Studio, and try describe what kind of error you will receive. During first run, application is waiting for authorization with plex account

I dont know how to do that

> Just now i tried released version, after authorization with plex, application will stay minimalized but you can show it from taskbar

https://streamable.com/f4aazd

**Comment by dhrinkino** [comment]
Oh i see you are using Windows 11, actually i never tried to run it on Windows 11 but at this moment i don't have a device with a W11. Please try to install .NET 5 Runtime for Desktop and try portable version. https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by Ravencentric** [comment]
![image](https://user-images.githubusercontent.com/78981416/144236275-c7bd3ceb-6e78-4629-85be-f7ae8e68787b.png)
Same issue persists

**Comment by dhrinkino** [comment]
Sorry for delay, I will try to check it on windows 11. I highly recommends you to download a source code, reinstall dependencies, remove signing in properties in visual studio 2022 and build solution and check behaviour

**Comment by Ravencentric** [comment]
> I highly recommends you to download a source code, reinstall dependencies, remove signing in properties in visual studio 2022 and build solution and check behaviour

I would if i could. Would you mind providing a bit more details? Apologies for being dumb lol.
I have Visual Studio Code 1.62.3

**Comment by dhrinkino** [comment]
I recommends you to download Visual Studio Community 2022 (have all deprendencies). Open .sln file wish VS2022. Expand project solution on right sidebar, delete "Plex Discord Presence_TemporaryKey.pfx". Click on Properties, signing and uncheck "sign the clickone". then click on green arrow "Start"

**Comment by Ravencentric** [comment]
After I pressed start, the browser opened for Plex login. After logging in I got this:
![image](https://i.slow.pics/eSmxOoFO.png)
I clicked on copy details and pasted them below.
```
System.ArgumentException
  HResult=0x80070057
  Message=Accessed JArray values with invalid key value: "@uri". Int32 array index expected.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Plex_Discord_Presence.PlexAuth.GetServer() in C:\Users\there\Documents\GitHub\PlexRichPresence\Plex Discord Presence\PlexAuth.cs:line 161
   at Plex_Discord_Presence.Form1..ctor() in C:\Users\there\Documents\GitHub\PlexRichPresence\Plex Discord Presence\Form1.cs:line 50
   at Plex_Discord_Presence.Program.Main() in C:\Users\there\Documents\GitHub\PlexRichPresence\Plex Discord Presence\Program.cs:line 19
```

**Comment by dhrinkino** [comment]
Oh i see, it's sounds like plex api have a issue and propably did not found your PMS. Do you have selfhosted plex server? What device you are using as plex server. Do you have any remote shared libraries?

**Comment by Ravencentric** [comment]
Plex server is on this same machine. 
> Do you have any remote shared libraries?

Yes, i do have some cloud drives mounted

**Comment by dhrinkino** [comment]
> Plex server is on this same machine.

Oh i see, plex probably handle different remote servers and local servers at this moment is implemented only remote servers functionality, so in future i will try to fix it. Thank you so much for your patience.

**Comment by Ravencentric** [comment]
Ah no worries! Will look forward to an update!
